version: '3.8'

services:
  backend:
    image: mercari-build-training/app:latest
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000

  frontend:
    image: mercari-build-training/web:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - backend
